const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/Reviews');

//for seeded data, will keep the given id's in the review and characteristics fields. If we come across duplicate id's overwrite the input review id with the autogenerated mongo ObjectId

let photoSchema = mongoose.Schema({
  url: String
});

let reviewSchema = mongoose.Schema({
  review_id: {type: Number, index: true},
  product_id: {type: Number, index: true},
  rating: Number,
  summary: String,
  recommend: Boolean,
  response: String,
  body: String,
  date: Number,
  reviewer_name: String,
  helpfulness: Number,
  reported: Boolean,
  photos: [photoSchema]
});

let ratingsMetadataSchema = mongoose.Schema({
  product_id: {type: Number, index: true},
  1: Number,
  2: Number,
  3: Number,
  4: Number,
  5: Number
});

let recommendedMetadataSchema = mongoose.Schema({
  product_id: {type: Number, index: true},
  0: Number,
  1: Number
});

let fitSchema = mongoose.Schema({
  id: Number,
  product_id: {type: Number, index: true},
  totalScore: Number,
  numReviews: Number
});

let lengthSchema = mongoose.Schema({
  id: Number,
  product_id: {type: Number, index: true},
  totalScore: Number,
  numReviews: Number
});

let comfortSchema = mongoose.Schema({
  id: Number,
  product_id: {type: Number, index: true},
  totalScore: Number,
  numReviews: Number
});

let qualitySchema = mongoose.Schema({
  id: Number,
  product_id: {type: Number, index: true},
  totalScore: Number,
  numReviews: Number
});

let Photo = mongoose.model('Photo', photoSchema);
let Review = mongoose.model('Review', reviewSchema);
let RatingsMeta = mongoose.model('RatingsMeta', ratingsMetadataSchema);
let RecMeta = mongoose.model('RecMeta', recommendedMetadataSchema);
let Fit = mongoose.model('Fit', fitSchema);
let Length = mongoose.model('Length', lengthSchema);
let Comfort = mongoose.model('Comfort', comfortSchema);
let Quality = mongoose.model('Quality', qualitySchema);

module.exports.Photo = Photo;
module.exports.Review = Review;
module.exports.RatingsMeta = RatingsMeta;
module.exports.RecMeta = RecMeta;
module.exports.Fit = Fit;
module.exports.Length = Length;
module.exports.Comfort = Comfort;
module.exports.Quality = Quality;

